fun foo() =;
var = val five
 fun foo() {
    
 }

 try {
    
 }
 catch(Exception e) {
    
 }